app.config(['$routeProvider',function($routeProvider){
	$routeProvider.when('/',{
		templateUrl:'pages/login/loginstart/login.html',
		controller:'loginCtrl'
	}).when('/register',{
		templateUrl:'pages/login/register/register.html',
		controller:'registerCtrl'
	}).when('/retriveP1',{
		templateUrl:'pages/login/retriveP1/retrievePassword1.html',
		controller:'retriveP1Ctrl'
	}).when('/retriveP2',{
		templateUrl:'pages/login/retriveP2/setPassword.html',
		controller:'retriveP2Ctrl'
	}).when('/mbkshelf',{
		templateUrl:'pages/shelf/my-bookshelf/my-bookshelf.html',
		controller:'mbkshelfCtrl'
	}).when('/searchWord',{
		templateUrl:'pages/shelf/searchWord/searchWord.html',
		controller:'searchWordCtrl'
	}).when('/titleSelection',{
		templateUrl:'pages/shelf/titleSelection/titleSelection.html',
		controller:'titleSelectionCtrl'
	}).when('/myData',{
		templateUrl:'pages/my/data/data.html',
		controller:'myDataCtrl'
	}).when('/feedBack',{
		templateUrl:'pages/my/feedBack/feedBack.html',
		controller:'feedBackCtrl'
	}).when('/mine',{
		templateUrl:'pages/my/my/my.html',
		controller:'mineCtrl'
	}).when('/myNews',{
		templateUrl:'pages/my/myNews/myNews.html',
		controller:'myNewsCtrl'
	}).when('/preference',{
		templateUrl:'pages/my/preference/preference.html',
		controller:'preferenceCtrl'
	}).when('/setting',{
		templateUrl:'pages/my/setting/setting.html',
		controller:'settingCtrl'
	}).when('/version',{
		templateUrl:'pages/my/version/version.html',
		controller:'versionCtrl'
	}).when('/recommend',{
		templateUrl:'pages/bookCity/recommend/recommend.html',
		controller:'recommendCtrl'
	}).when('/weeklyChart',{
		templateUrl:'pages/bookCity/weeklyChart/weeklyChart.html',
		controller:'weeklyChartCtrl'
	}).when('/atBooks',{
		templateUrl:'pages/bookpage/allTheBooks/allTheBooks.html',
		controller:'atBooksCtrl'
	}).when('/bookMark',{
		templateUrl:'pages/bookpage/bookMark/bookMark.html',
		controller:'bookMarkCtrl'
	}).when('/comment',{
		templateUrl:'pages/bookpage/comment/comment.html',
		controller:'commentCtrl'
	}).when('/note',{
		templateUrl:'pages/bookpage/note/note.html',
		controller:'noteCtrl'
	}).when('/bPages',{
		templateUrl:'pages/bookpage/pages/pages.html',
		controller:'bPagesCtrl'
	}).when('/readbooks',{
		templateUrl:'pages/reading/readbooks/readBooks.html',
		controller:'readbooksCtrl'
	}).when('/booktitle',{
		templateUrl:'pages/bookCity/booktitle/selected.html',
		controller:'booktitleCtrl'
	})
}])